#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{ $masterCount := int .Values.master.count }}
{{- $release := .Release }}
{{- $name := include "goosefs.name" . }}
{{- $fullName := include "goosefs.fullname" . }}
{{- $chart := include "goosefs.chart" . }}
{{- range $i := until $masterCount }}
  {{- $masterName := printf "master-%v" $i }}
  {{- $masterJavaOpts := printf " -Dgoosefs.master.hostname=%v-%v " $fullName $masterName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $masterName }}
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $release.Name }}
    heritage: {{ $release.Service }}
    role: goosefs-master
spec:
  ports:
    - port: 9200
      name: rpc
    - port: 9201
      name: web
    - port: 9205
      name: job-rpc
    - port: 9206
      name: job-web
    - port: 9203
      name: embedded
    - port: 9207
      name: job-embedded
  clusterIP: None
  selector:
    role: goosefs-master
    app: {{ $name }}
    release: {{ $release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $fullName }}-{{ $masterName }}
---
{{- end }}
